
package com.webservices;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "tranBookingInfo", targetNamespace = "http://booking", wsdlLocation = "http://128.100.200.122:8888/WS_HSBY_BOOKING/services/tranBookingInfo?wsdl")
public class TranBookingInfo
    extends Service
{

    private final static URL TRANBOOKINGINFO_WSDL_LOCATION;
    private final static WebServiceException TRANBOOKINGINFO_EXCEPTION;
    private final static QName TRANBOOKINGINFO_QNAME = new QName("http://booking", "tranBookingInfo");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://128.100.200.122:8888/WS_HSBY_BOOKING/services/tranBookingInfo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRANBOOKINGINFO_WSDL_LOCATION = url;
        TRANBOOKINGINFO_EXCEPTION = e;
    }

    public TranBookingInfo() {
        super(__getWsdlLocation(), TRANBOOKINGINFO_QNAME);
    }

    public TranBookingInfo(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANBOOKINGINFO_QNAME, features);
    }

    public TranBookingInfo(URL wsdlLocation) {
        super(wsdlLocation, TRANBOOKINGINFO_QNAME);
    }

    public TranBookingInfo(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANBOOKINGINFO_QNAME, features);
    }

    public TranBookingInfo(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TranBookingInfo(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TranBookingInfoPortType
     */
    @WebEndpoint(name = "tranBookingInfoHttpPort")
    public TranBookingInfoPortType getTranBookingInfoHttpPort() {
        return super.getPort(new QName("http://booking", "tranBookingInfoHttpPort"), TranBookingInfoPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TranBookingInfoPortType
     */
    @WebEndpoint(name = "tranBookingInfoHttpPort")
    public TranBookingInfoPortType getTranBookingInfoHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://booking", "tranBookingInfoHttpPort"), TranBookingInfoPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANBOOKINGINFO_EXCEPTION!= null) {
            throw TRANBOOKINGINFO_EXCEPTION;
        }
        return TRANBOOKINGINFO_WSDL_LOCATION;
    }

}
